import os
import sys
import pickle
import tkinter as tk
from tkinter import messagebox, scrolledtext, filedialog

# Check for dependency immediately
try:
    import lumicks.pylake as lk
except ImportError:
    messagebox.showerror("Dependency Error", 
        "The 'lumicks-pylake' package is required to read these files.\n\n"
        "Please install it via:\npip install lumicks-pylake")
    sys.exit(1)

# Global variable to hold the text widget
log_output = None

def inspect_and_display(filepath):
    """Loads the pkl file and populates the GUI text area."""
    global log_output
    
    if log_output is None:
        messagebox.showerror("Error", "GUI not ready yet.")
        return

    log_output.config(state=tk.NORMAL)
    log_output.delete("1.0", tk.END)
    
    filename = os.path.basename(filepath)
    log_output.insert(tk.END, f"--- Inspecting: {filename} ---\n")
    log_output.insert(tk.END, f"File Path: {filepath}\n")
    log_output.insert(tk.END, "-" * 50 + "\n\n")

    try:
        with open(filepath, 'rb') as f:
            data = pickle.load(f)
            
        if not isinstance(data, dict):
            log_output.insert(tk.END, f"⚠️ Warning: File does not contain a dictionary. Type found: {type(data)}\n")
            return

        keys = list(data.keys())
        log_output.insert(tk.END, f"Found {len(keys)} saved models/objects:\n")
        
        for key in keys:
            value = data[key]
            log_output.insert(tk.END, f"\n{'='*30}\nKey: '{key}'\nType: {type(value).__name__}\n")
            
            # Check if it's a Pylake FdFit object
            if isinstance(value, lk.FdFit):
                status = "Success" if hasattr(value, 'fit_status') and value.fit_status else "Unknown"
                try:
                    ll = value.log_likelihood()
                    log_output.insert(tk.END, f"  • Status: {status}\n  • Log-Likelihood: {ll:.4f}\n")
                except:
                    log_output.insert(tk.END, f"  • Status: {status}\n  • Log-Likelihood: [Could not calculate]\n")
                
                log_output.insert(tk.END, "  • Parameters:\n")
                params = value.params
                for param_name in params:
                    try:
                        p = params[param_name]
                        raw_val = p.value if hasattr(p, 'value') else None
                        raw_err = p.stderr if hasattr(p, 'stderr') else None
                        unit = getattr(p, 'unit', '') or ''
                        is_fixed = getattr(p, 'fixed', False)

                        # Handle None values from fixed parameters
                        if raw_val is None:
                            val_str = "    N/A"
                        else:
                            val_str = f"{raw_val:>10.4f}"

                        if raw_err is None or raw_err == 0:
                            err_str = "   (fixed)"
                        else:
                            err_str = f"± {raw_err:>8.4f}"

                        line = f"      - {param_name:<30}: {val_str} {err_str} {unit}"
                        log_output.insert(tk.END, line + "\n")
                    except Exception as e:
                        log_output.insert(tk.END, f"      - {param_name}: [Error: {str(e)[:40]}]\n")
            elif hasattr(value, '__dict__'):
                attrs = list(value.__dict__.keys())
                log_output.insert(tk.END, f"  • Attributes ({len(attrs)}): {', '.join(attrs[:5])}... (truncated)\n")
            else:
                preview = str(value)[:100]
                log_output.insert(tk.END, f"  • Value: {preview}...\n")

    except pickle.UnpicklingError as e:
        log_output.insert(tk.END, f"❌ Critical Error unpickling file: {e}\n")
    except Exception as e:
        log_output.insert(tk.END, f"❌ Unexpected Error: {e}\n")
    finally:
        log_output.config(state=tk.DISABLED)

def browse_file():
    """Opens system file explorer to select a .pkl file."""
    filepath = filedialog.askopenfilename(
        title="Select FRIED POTATO Model File",
        filetypes=[("Pickle files", "*.pkl"), ("All files", "*.*")]
    )
    
    if filepath:
        inspect_and_display(filepath)

def main():
    global log_output

    # Create Main Window
    root = tk.Tk()
    root.title("FRIED POTATO .pkl Inspector")
    root.geometry("900x600")
    
    # Frame for Buttons
    btn_frame = tk.Frame(root, pady=10)
    btn_frame.pack(fill=tk.X)
    
    lbl_instruction = tk.Label(btn_frame, text="Click below to choose a .pkl file generated by FRIED POTATO:", font=("Arial", 10))
    lbl_instruction.pack(pady=5)
    
    btn_browse = tk.Button(btn_frame, text="📂 Select File...", command=browse_file, bg="#4CAF50", fg="white", font=("Arial", 12, "bold"))
    btn_browse.pack(pady=5)
    
    # Text Area for Output
    output_frame = tk.Frame(root)
    output_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=5)
    
    lbl_log = tk.Label(output_frame, text="Analysis Log:", font=("Arial", 9, "bold"))
    lbl_log.pack(anchor="w")
    
    # Initialize the global text widget
    log_output = scrolledtext.ScrolledText(output_frame, wrap=tk.WORD, font=("Courier", 10), state=tk.DISABLED)
    log_output.pack(fill=tk.BOTH, expand=True)
    
    # Initial message
    log_output.config(state=tk.NORMAL)
    log_output.insert(tk.END, "Ready. Please select a file to inspect.\n")
    log_output.config(state=tk.DISABLED)
    
    root.mainloop()

if __name__ == "__main__":
    main()